title: Federico Natali 
logo: "/images/circle-cropped.png?raw=true"
description: > # your text below 
  
  <br><br>
  <a href="https://www.linkedin.com/in/federico-natali/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://angel.co/u/natalifederico">View My Angel.co Account</a>
  <br><br>
  <a href="https://mobile.twitter.com/federico_light/">View My Twitter Account</a>
  <br><br>
  My favorite quote is "By virtue of exchange one man's prosperity is beneficial to all others" by Frederic Bastiat.
  <br><br>
  I am a supporter of both the Mises Institute and the Electronic Frontier Foundation
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
